export * from '../startGame/game';
export * from './data';
export * from '../sort/sortCards';
export * from '../filters/filterByFavorite';
export * from '../filters/filterByColor';
export * from '../filters/filterBySize';
export * from '../filters/resetFilters';
export * from '../toys/searchToys';
export * from '../filters/rangeFilters';
export * from '../filters/totalFilters';
export * from '../filters/filterByShape';
export * from '../toys/selectedToys';
export * from '../toys/createCardToys';
export * from '../garland/garland';
export * from '../tree/createPageTree';
export * from '../filters/fillToysSlots';
export * from '../tree/settingsForTree';
export * from '../toys/moveToys';
export * from '../tree/coordsArea';
export * from './instance';

export const mainPage = document.querySelector('.main') as HTMLElement;
export const countSelectedShow = document.querySelector('.total-favorite') as HTMLElement;
export const amountSelectedToys = document.querySelector('.total-favorite') as HTMLElement;
export const sortSelect = document.querySelector('.sort-select') as HTMLSelectElement;
export const white = document.querySelector('.white') as HTMLElement;
export const inputWhite = document.querySelector('.input-white') as HTMLInputElement;
export const yellow = document.querySelector('.yellow') as HTMLElement;
export const inputYellow = document.querySelector('.input-yellow') as HTMLInputElement;
export const red = document.querySelector('.red') as HTMLElement;
export const inputRed = document.querySelector('.input-red') as HTMLInputElement;
export const blue = document.querySelector('.blue') as HTMLElement;
export const inputBlue = document.querySelector('.input-blue') as HTMLInputElement;
export const green = document.querySelector('.green') as HTMLElement;
export const inputGreen = document.querySelector('.input-green') as HTMLInputElement;
export const ball = document.querySelector('.shape-ball') as HTMLElement;
export const bell = document.querySelector('.shape-bell') as HTMLElement;
export const cone = document.querySelector('.shape-cone') as HTMLElement;
export const snowflake = document.querySelector('.shape-snowflake') as HTMLElement;
export const toy = document.querySelector('.shape-toy') as HTMLElement;
export const large = document.querySelector('.large') as HTMLElement;
export const medium = document.querySelector('.medium') as HTMLElement;
export const small = document.querySelector('.small') as HTMLElement;
export const slidersAmount = document.querySelectorAll('.input-range-amount') as unknown as HTMLInputElement[];
export const startAmount = document.querySelector('.start-amount') as HTMLOutputElement;
export const endAmount = document.querySelector('.end-amount') as HTMLOutputElement;
export const slidersYear = document.querySelectorAll('.input-range-year') as unknown as HTMLInputElement[];
export const startYear = document.querySelector('.start-year') as HTMLOutputElement;
export const endYear = document.querySelector('.end-year') as HTMLOutputElement;
export const progressAmount = document.querySelector('.progress-line-amount') as HTMLElement;
export const progressYear = document.querySelector('.progress-line-year') as HTMLElement;
export const inputSearch = document.querySelector('.search') as HTMLInputElement;
export const inputSearchWrap = document.querySelector('.input-search-wrap') as HTMLElement;
export const messageAfterFiltering = document.querySelector('.message-after-filtering') as HTMLElement;
export const toysSlot = document.querySelector('.toys-slot') as HTMLElement;
export const startPage = document.querySelector('.main__page') as HTMLElement;
export const pageToys = document.querySelector('.main__page-toys') as HTMLElement;
export const pageTree = document.querySelector('.main__page-tree') as HTMLElement;
export const buttonStart = document.querySelector('.start-game') as HTMLElement;
export const iconMainPage = document.querySelector('.icon-main-page') as HTMLElement;
export const linkToToysPage = document.querySelector('.page-toys') as HTMLElement;
export const linkToTreePage = document.querySelector('.page-christmas-tree') as HTMLElement;
export const searchWrap = document.querySelector('.search-wrap') as HTMLElement;
export const switchGarland = document.querySelector('.on-or-off-garland') as HTMLInputElement;
export const tree = document.querySelector('.tree') as HTMLElement;
export const treeWrap = document.querySelector('.tree-wrap') as HTMLElement;
export const resetSettings = document.querySelector('.reset-settings') as HTMLElement;
export const area = document.querySelector('area') as HTMLElement;
export const buttonSound = document.querySelector('.sound') as HTMLElement;
