import {CoordsArea} from "../tree/coordsArea";
import {Card} from "../toys/createCardToys";
import {Sort} from "../sort/sortCards";
import {Search} from "../toys/searchToys";
import {PageTree} from "../tree/createPageTree";
import {TotalFilters} from "../filters/totalFilters";
import {FilterByShape} from "../filters/filterByShape";
import {FilterBySize} from "../filters/filterBySize";
import {FilterByFavorite} from "../filters/filterByFavorite";
import {FilterByColor} from "../filters/filterByColor";
import {Selected} from "../toys/selectedToys";
import {RangeFilters} from "../filters/rangeFilters";
import {Garland} from "../garland/garland";
import {Game} from "../startGame/game";

export const coordsArea = new CoordsArea();
export const card = new Card();
export const sort = new Sort();
export const search = new Search();
export const objPageTree = new PageTree();
export const totalFilters = new TotalFilters();
export const filterByShape = new FilterByShape();
export const filterBySize = new FilterBySize();
export const filterByFavorite = new FilterByFavorite();
export const filterByColor = new FilterByColor();
export const selected = new Selected();
export const rangeFilters = new RangeFilters();
export const garland = new Garland();
export const game = new Game();
